# Generated by Django 3.1 on 2020-08-25 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('skill',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='MediaTechnology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='skills',
            field=models.ManyToManyField(to='posts.Skills'),
        ),
    ]
